### ISSUE TITLE
Add strict mocks to ts-mockito

### ISSUE THREAD

**Issue by colinbreame-scout24** [NagRock/ts-mockito#153]
ts-mockito does not support strict mocks like the Java version, see https://github.com/mockito/mockito/issues/1097.

Strict mocks are a great way to ensure you have mocked everything you think you have, and to spot changes in behaviour.

**Comment by NagRock** [comment]
Hi, thanks for reporting this but I think this is not possible with current implementation. Because of interfaces and because in runtime with TS we don't have reflection tools, `ts-mockito` tries to handle as much functions / properties names as possible. Even those that doesn't exists in mocked class. I think that without TS compiler plugins public API it is impossible.
