### ISSUE TITLE
Support for getters/setters

### ISSUE THREAD

**Issue by manda-linda** [NagRock/ts-mockito#29]
It looks like getters and setters are not currently supported. Is there a plan for this in the future?

Example:
```
class LocationUtility {
    public get routeParams():  any {
         return {};
    }
}
```

The below code will result in an error: "Uncaught TypeError: Cannot read property 'proof' of undefined"
```
let location = mock(LocationUtility);
instance(location).routeParams.id 
```

**Comment by NagRock** [comment]
When I run yours code I get:

`TypeError: null is not an object (evaluating 'ts_mockito_1.instance(location).routeParams.id')`

Because you are not mocking `routeParams` so it is `null` but error that you are getting is really strange because there is no `proof` property in code that you shared.

Which version are you using?
Is that all code that you got?

**Comment by manda-linda** [comment]
Sorry, my example code is an abridged version of the code I was actually running. The error shoudl be "Uncaught TypeError: Cannot read property 'id' of undefined"

**Comment by NagRock** [comment]
So it is because you didn't set expected behavior. 
Try this:
```
        let location = mock(LocationUtility);
        when(location.routeParams).thenReturn({id: "sampleMockedId"})
        console.log(instance(location).routeParams.id);```

**Comment by manda-linda** [comment]
Oh, duhhh. My bad. Thanks!
