### ISSUE TITLE
spy support

### ISSUE THREAD

**Issue by gabrielguerrero** [NagRock/ts-mockito#33]
Hey guys, 
Any plan on supporting spy in the same style as java mockito does? the library is fantastic by the way
Kind Regards
Gabriel

**Comment by NagRock** [comment]
@gabrielguerrero yes I have plans to add spy functionality. Thanks for motivating words :)

**Comment by viswanadha-kondoju-ck** [comment]
@NagRock when can we expect the spy functionality

**Comment by dreef3** [comment]
Hi @NagRock ,

First of all, thanks for your great work, I use it at work and typed mocking is a great advance over Jasmine's `spyOn`.

Could you please share your thoughts about how the spy functionality would look like? I'd submit a PR then.

What do you think about the following approach:
```
function spy(instance: T): T {
    return new Spy(instance).getMock();
}
```

The `Spy` class would extend a `Mocker`. It would create another object with `instance` as a prototype and return it. The behaviour would be similar to the existing `Mocker` but instead of this:
https://github.com/NagRock/ts-mockito/blob/master/src/Mock.ts#L247
it would call a real method.

**Comment by NagRock** [comment]
@viswanadha-kondoju-ck sorry for late reply. I think that spy support will be added within 2 weeks.

**Comment by NagRock** [comment]
Thanks to @dreef3 we got new release `2.2.0` with spy support: https://github.com/NagRock/ts-mockito/releases/tag/v2.2.0

**Comment by viman** [comment]
Great job guys! Special thanks to @dreef3

**Comment by viswanadha-kondoju-ck** [comment]
Great job and thanks :)
