### ISSUE TITLE
Mocking class with constructor arguments

### ISSUE THREAD

**Issue by artman** [NagRock/ts-mockito#74]
Say we have a class like so:

```
export default class FileLoader {
  private fileToLoad: string
  public constructor(fileToLoad: string) {
    this.fileToLoad = fileToLoad;
    this.loadFile(); 
  }

  private loadFile() {
    ...
  }
}
```

I don't see any way to create a mock of the FileLoader and and instantiate it and pass parameters to the constructor.

**Comment by NagRock** [comment]
Why you want to pass arguments to mock? Mock has no implementation so constructor code would not be executed even if you pass arguments. Can you give an example what you try to do?

**Comment by artman** [comment]
Sure, given the example above, I would like to stub out the implementation of loadFile to test whether the fileToLoad property has been set correctly.
```
// In my test
const fileLoaderMock = mock(FileLoader);
when(fileLoaderMock.loadFile).thenExecute( /* Verify that fileToLoad property has been set */)
instance(fileLoaderMock) // And here I'd need to pass in the constructor parameters.
```

**Comment by NagRock** [comment]
Hi again. First of all you can use syntax like:
`public constructor(private fileToLoad: string) {` and then you don't have to worry about this if `fileToLoad` has been set.
Secondly `fileToLoad` so you would not be able to check if `loadFile` has been set.
And finally if you want the constructor to be called you should use `spy` instead of `mock`.
